import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:3000/login');
  await page.getByRole('textbox', { name: 'Ej: admin' }).click();
  await page.getByRole('textbox', { name: 'Ej: admin' }).fill('admin');
  await page.getByRole('textbox', { name: '••••••••' }).click();
  await page.getByRole('textbox', { name: '••••••••' }).fill('tesocol2025');
  await page.getByRole('button', { name: 'Ingresar al Sistema' }).click();
  await page.getByRole('link', { name: 'Dashboard' }).click();
  await page.getByRole('link', { name: 'Inventario' }).click();
  await page.getByRole('link', { name: 'Proyectos / Obras' }).click();
  await page.getByRole('link', { name: 'Despachos' }).click();
  await page.getByRole('link', { name: 'Reportes PDF' }).click();
  await page.getByRole('link', { name: 'Exportar Excel' }).click();
  await page.getByRole('link', { name: 'Dashboard' }).click();
  await page.getByRole('link', { name: 'Inventario' }).click();
  await page.getByRole('button', { name: 'Nuevo Material' }).click();
  await page.getByRole('textbox', { name: 'Ej: Panel Solar 550W' }).click();
  await page.getByRole('textbox', { name: 'Ej: Panel Solar 550W' }).fill('paneles ');
  await page.getByRole('textbox', { name: 'Ej: Panel Solar 550W' }).press('Tab');
  await page.getByRole('textbox', { name: 'Ej: PS-550W-MONO' }).fill('12343');
  await page.getByRole('textbox', { name: 'Ej: PS-550W-MONO' }).press('CapsLock');
  await page.getByRole('spinbutton').first().dblclick();
  await page.getByRole('spinbutton').first().fill('');
  await page.getByRole('spinbutton').first().click();
  await page.getByRole('spinbutton').first().dblclick();
  await page.getByRole('spinbutton').first().click();
  await page.getByRole('spinbutton').first().dblclick();
  await page.getByRole('spinbutton').first().fill('');
  await page.getByRole('spinbutton').first().press('ArrowLeft');
  await page.getByRole('spinbutton').first().fill('');
  await page.getByRole('spinbutton').first().press('ArrowLeft');
  await page.getByRole('spinbutton').first().fill('20');
  await page.getByRole('textbox', { name: 'Ej: Estante A-' }).click();
  await page.getByRole('textbox', { name: 'Ej: Estante A-' }).fill('BODEGA ');
  await page.getByRole('textbox', { name: 'Ej: Estante A-' }).press('Tab');
  await page.getByRole('textbox', { name: 'Nombre del proveedor' }).fill('DM');
  await page.getByRole('button', { name: '💾 Guardar' }).click();
  await page.getByRole('button', { name: 'Nuevo Material' }).click();
  await page.locator('label').filter({ hasText: 'Categoría' }).click();
  await page.getByRole('link', { name: 'Proyectos / Obras' }).click();
  await page.getByRole('button', { name: 'Nueva Obra' }).click();
  await page.getByRole('textbox', { name: 'Ej: Peñatex Cali — Sistema FV' }).click();
  await page.getByRole('textbox', { name: 'Ej: Peñatex Cali — Sistema FV' }).fill('TESOCOL');
  await page.getByRole('textbox', { name: 'Ej: Peñatex Cali — Sistema FV' }).press('Tab');
  await page.getByRole('textbox', { name: 'Descripción del proyecto...' }).fill('VISITA TECNICA');
  await page.getByRole('textbox', { name: 'Descripción del proyecto...' }).press('Tab');
  await page.getByRole('textbox', { name: 'Nombre completo' }).fill('LUIS');
  await page.getByRole('textbox', { name: 'Nombre completo' }).press('Tab');
  await page.getByRole('textbox', { name: 'Ej: Cali, Valle del Cauca' }).fill('PALMIRA ');
  await page.getByRole('textbox', { name: 'Ej: Cali, Valle del Cauca' }).press('Tab');
  await page.getByRole('button', { name: '💾 Crear' }).click();
  await page.getByRole('main').getByText('TESOCOL').click();
  await page.getByRole('button', { name: 'Despachar' }).click();
  await page.locator('.animate-modal > div:nth-child(2) > div:nth-child(2)').click();
  await page.getByRole('combobox').selectOption('mo1ph1a5z92ehmhs8ka');
  await page.getByRole('spinbutton').click();
  await page.getByRole('spinbutton').fill('8');
  await page.getByRole('textbox', { name: 'Nombre', exact: true }).click();
  await page.getByRole('textbox', { name: 'Nombre', exact: true }).fill('LUIS');
  await page.getByRole('button', { name: '🚚 Confirmar Despacho' }).click();
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('button', { name: 'PDF' }).click();
  const download = await downloadPromise;
  await page.getByRole('link', { name: 'Inventario' }).click();
  await page.getByRole('link', { name: 'Reportes PDF' }).click();
  const download1Promise = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Generar PDF' }).first().click();
  const download1 = await download1Promise;
  await page.locator('div').filter({ hasText: '📦Inventario CompletoPDF con' }).nth(2).click();
  const download2Promise = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Generar PDF' }).nth(1).click();
  const download2 = await download2Promise;
});